# Generated by Django 5.1 on 2026-09-28 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации в системе')),
                ('fn', models.CharField(max_length=16, verbose_name='ФН (фискальный накопитель)')),
                ('fd', models.CharField(max_length=10, verbose_name='ФД (фискальный документ)')),
                ('fp', models.CharField(max_length=10, verbose_name='ФП (фискальный призрак)')),
                ('purchase_date', models.DateTimeField(verbose_name='Дата и время покупки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма чека')),
                ('status', models.CharField(choices=[('checking', 'На проверке'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='checking', max_length=10, verbose_name='Статус')),
                ('reject_reson', models.TextField(blank=True, null=True, verbose_name='Причина отказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-registration_date'],
                'constraints': [models.UniqueConstraint(fields=('fn', 'fd', 'fp'), name='unique_fn_fd_fp_receipt')],
            },
        ),
    ]
