# Generated by Django 5.1 on 2026-09-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='reject_reson',
            new_name='reject_reason',
        ),
    ]
